$color = rgba(24, 18, 12, 1)
$inner_color = rgba(24, 18, 12, 1)
$outer_color = rgba(164, 148, 130, 0.5)
$font_color = rgba(237, 224, 213, 1)
$placeholder_color = rgba(237, 224, 213, 0.6)
$check_color = rgba(255, 185, 83, 1.0)
