# Ghostty Theme: snow_black (matugen fallback)
background = #121412
foreground = #e3e3df
cursor-color = #e3e3df

palette = 0=#121412
palette = 1=#ffb4ab
palette = 2=#bdcabc
palette = 3=#efbac1
palette = 4=#afd0b3
palette = 5=#afd0b3
palette = 6=#bdcabc
palette = 7=#e3e3df
palette = 8=#424842
palette = 9=#ffb4ab
palette = 10=#bdcabc
palette = 11=#efbac1
palette = 12=#afd0b3
palette = 13=#afd0b3
palette = 14=#bdcabc
palette = 15=#e3e3df
