# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = wl-paste --watch cliphist store
exec-once = swaybg -i ~/.config/theme/current/background -m fill
exec-once = quickshell -p ~/.config/quickshell
exec-once = pkill -x swayosd-server
exec-once = FILEMANAGER_PORTAL_IDLE=0 ~/projects/filemanager/tools/filemanager-portal  # owns the FileChooser backend; spawns picker windows
