# System Monitor — quickshell floating window
windowrule = float on, match:class quickshell, match:title System Monitor
windowrule = center on, match:class quickshell, match:title System Monitor
windowrule = size 920 640, match:class quickshell, match:title System Monitor

# uthmanHabit — habit tracker Hyprland window (small)
windowrule = float on, match:class org.quickshell, match:title uthmanHabit
windowrule = center on, match:class org.quickshell, match:title uthmanHabit
windowrule = size 440 440, match:class org.quickshell, match:title uthmanHabit
