# System Monitor — quickshell floating window
windowrule = float on, match:class quickshell, match:title System Monitor
windowrule = center on, match:class quickshell, match:title System Monitor
windowrule = size 920 640, match:class quickshell, match:title System Monitor

# PhoneLink — small centered popup like the System card
windowrule = float on, match:class quickshell, match:title PhoneLink
windowrule = center on, match:class quickshell, match:title PhoneLink
windowrule = size 400 520, match:class quickshell, match:title PhoneLink
windowrule = float on, match:class org.quickshell, match:title PhoneLink
windowrule = center on, match:class org.quickshell, match:title PhoneLink
windowrule = size 400 520, match:class org.quickshell, match:title PhoneLink

# Package Manager — quickshell floating window (Hyprland window, not popup)
windowrule = float on, match:class quickshell, match:title Package Manager
windowrule = center on, match:class quickshell, match:title Package Manager
windowrule = size 980 640, match:class quickshell, match:title Package Manager
windowrule = float on, match:class org.quickshell, match:title Package Manager
windowrule = center on, match:class org.quickshell, match:title Package Manager
windowrule = size 980 640, match:class org.quickshell, match:title Package Manager

# uthmanHabit — habit tracker Hyprland window (small)
windowrule = float on, match:class org.quickshell, match:title uthmanHabit
windowrule = center on, match:class org.quickshell, match:title uthmanHabit
windowrule = size 440 440, match:class org.quickshell, match:title uthmanHabit

# Screensaver — ghostty fullscreen, no decorations
windowrule = float on, match:class org.screensaver
windowrule = fullscreen on, match:class org.screensaver


# Zathura — glass float
windowrule = float on, match:class ^(org.pwmt.zathura)$
windowrule = center on, match:class ^(org.pwmt.zathura)$
windowrule = size 1100 750, match:class ^(org.pwmt.zathura)$
windowrule = opacity 0.88 0.82, match:class ^(org.pwmt.zathura)$

# mpv — centered floating popup
windowrule = float on, match:class ^(mpv)$
windowrule = center on, match:class ^(mpv)$
windowrule = size 960 540, match:class ^(mpv)$

# filemanager picker — centered floating popup, same treatment as mpv
windowrule = float on, match:class ^(com.codetesla51.filemanager.picker)$
windowrule = center on, match:class ^(com.codetesla51.filemanager.picker)$
windowrule = size 960 540, match:class ^(com.codetesla51.filemanager.picker)$
