import QtQuick 2.0
// AUTO-GENERATED by matugen — do not edit.
// Source: ~/.config/matugen/templates/sddm-palette.qml
QtObject {
    property color background: "#131314"
    property color surface: "#131314"
    property color outline: "#939799"
    property color text: "#e4e2e1"
    property color primary: "#bfc8cc"
    property color error: "#ffb4ab"
}
