import QtQuick 2.0
// AUTO-GENERATED by matugen — do not edit.
// Source: ~/.config/matugen/templates/sddm-palette.qml
QtObject {
    property color background: "#18120c"
    property color surface: "#18120c"
    property color outline: "#a49482"
    property color text: "#ede0d5"
    property color primary: "#ffb953"
    property color error: "#ffb4ab"
}
