import QtQuick 2.0
// AUTO-GENERATED by matugen — do not edit.
// Source: ~/.config/matugen/templates/sddm-palette.qml
QtObject {
    property color background: "{{colors.background.default.hex}}"
    property color surface: "{{colors.surface.default.hex}}"
    property color outline: "{{colors.outline.default.hex}}"
    property color text: "{{colors.on_background.default.hex}}"
    property color primary: "{{colors.primary.default.hex}}"
    property color error: "{{colors.error.default.hex}}"
}
